
public class Movie {

	private int title;
	private int category;
	
	public Movie(int t, int c){
		title = t;
		category = c;
	}
	
	public String[][]movieArray = new String[][]{
	horror.add[0] =  "Scary Movie", 
	movieArray[1] = "Scary Movie 2",
	movieArray[0][2] = "Scary Movie 3",
	movieArray[0][3] = "Scary Movie 4",
	movieArray[0][4] =  "Scary Movie5",
	movieArray[0][5] =  "Poltergiest",
	movieArray[0][6] = "Poltergiest 2",
	movieArray[0][7] = "Poltergiest 3",
	movieArray[0][8] = "Chucky",
	movieArray[0][9] = "Chucky 2",
	movieArray[0][10] = "Bride of Chucky",
	movieArray[0][11] = "Pet Semitary",
	movieArray[0][12] = "It",
	movieArray[0][13] = "Gremlins",
	movieArray[0][14] = "Gremlins 2",
	movieArray[0][15] = "Cape Fear",
	movieArray[0][16] = "Saw",
	movieArray[0][17] = "Saw 2",
	movieArray[0][18] = "Saw 3",
	movieArray[0][19] = "Saw 4",
	movieArray[0][20] = "Saw 5",
	movieArray[0][21] = "Scream",
	movieArray[0][22] = "Scream 2",
	movieArray[0][23] = "Scream 3",
	movieArray[0][24] = "Scream 4",
			
	movieArray[1][0] = "Toy Story",
	movieArray[1][1] = "Toy Story 2",
	movieArray[1][2] = "Toy Story 3",
	movieArray[1][3] = "Beauty and the Beast",
	movieArray[1][4] = "Cars",
	movieArray[1][5] = "Cars 2",
	movieArray[1][6] = "Aladdin",
	movieArray[1][7] = "Secret Life of Pets",
	movieArray[1][8] = "Storks",
	movieArray[1][9] = "Sleeping Beauty",
	movieArray[1][10] = "Snow White",
	movieArray[1][11] = "Cinderella",
	movieArray[1][12] = "Simpsons",
	movieArray[1][13] = "Boondocks",
	movieArray[1][14] = "Bob's Burgers",
	movieArray[1][15] = "SpongeBob",
	movieArray[1][16] = "Teen Titals",
	movieArray[1][17] = "Snoopy",
	movieArray[1][18] = "Tom and Jerry",
	movieArray[1][19] = "Rug Rats",
	movieArray[1][20] = "Pokemon",
	movieArray[1][21] = "Yokai",
	movieArray[1][22] = "Yugio",
	movieArray[1][23] = "Finding Nemo",
	movieArray[1][24] = "Finding Dory",
	
	movieArray[2][0] = "Bringing Down the House",
	movieArray[2][1] = "Friday",
	movieArray[2][2] = "Central Intelligence",
	movieArray[2][3] = "White Chicks",
	movieArray[2][4] = "Big Mama's House",
	movieArray[2][5] = "Big Mama's House 2",
	movieArray[2][6] = "Are We There Yet?",
	movieArray[2][7] = "Bay-Bay's Kids",
	movieArray[2][8] = "Kings of Comedy",
	movieArray[2][9] = "The Boss",
	movieArray[2][10] = "Keanu",
	movieArray[2][11] = "Next Friday",
	movieArray[2][12] = "Friday After Next",
	movieArray[2][13] = "Baps",
	movieArray[2][14] = "How to be a player",
	movieArray[2][15] = "Airplane",
	movieArray[2][16] = "Spaceballs",
	movieArray[2][17] = "Soul Plane",
	movieArray[2][18] = "Grandma's Boy",
	movieArray[2][19] = "Get Him to the Greek",
	movieArray[2][20] = "Coming to America",
	movieArray[2][21] = "Something about Mary",
	movieArray[2][22] = "SuperBad",
	movieArray[2][23] = "40 year-old Virgin",
	movieArray[2][24] = "Bridesmaids",
	
	movieArray[3][0] = "Star Wars 1",
	movieArray[3][1] = "Star Wars 2",
	movieArray[3][2] = "Star Wars 3",
	movieArray[3][3] = "Star Wars 4",
	movieArray[3][4] = "Star Wars 5",
	movieArray[3][5] = "Star Wars 6",
	movieArray[3][6] = "Star Wars 7",
	movieArray[3][7] = "Star Wars 8",
	movieArray[3][8] = "Star Wars 9",
	movieArray[3][9] = "Star Trek",
	movieArray[3][10] = "Close Encounters of the Third Kind",
	moveArray[3][11] = "ET",
	movieArray[3][12] = "Total Recall",
	movieArray[3][13] = "The Fifth Element",
	movieArray[3][14] = "The Matrix",
	movieArray[3][15] = "Jurassic Park",
	movieArray[3][16] = "Terminator",
	movieArray[3][17] = "Robocop",
	movieArray[3][18] = "X-Men",   
	movieArray[3][19] = "X-Men Apocolypse",
	movieArray[3][20] = "Wizard of Oz",
	movieArray[3][21] = "Terminator 2",
	movieArray[3][22] = "Never Ending Story",
	movieArray[3][23] = "Mad Max",
	movieArray[3][24] = "Starship Troopers",
	
	String movieTitle = movieArray[category][title];
		return movieTitle;
		
	}//end array
}//end class